version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 30
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '08:20'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: '@types/node'
        versions: '>=20'
