name: build-actions
run-name: ${{ github.workflow }} workflow
on:
  pull_request_target:
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Set AWS Account Information
        run: |
          if [[ ${{ github.base_ref }} == 'dev' ]]; then
            echo "ROLE_TO_ASSUME=arn:aws:iam::${{ secrets.DEV_ACCOUNT_ID }}:role/ghac-cdk-deploy-role" >> $GITHUB_ENV
          elif [[ ${{ github.base_ref }} == 'main' ]]; then
            echo "ROLE_TO_ASSUME=arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/ghac-cdk-deploy-role" >> $GITHUB_ENV
          fi
          echo "DEV_ACCOUNT_ID=${{ secrets.DEV_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "PROD_ACCOUNT_ID=${{ secrets.PROD_ACCOUNT_ID }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/build

      - uses: actions/github-script@v7
        env:
          DIFF: "cdk diff\n${{ steps.diff.outputs.stdout }}"
          SNAPSHOT: "snapshot testing\n${{ steps.snapshot.outputs.stdout }}"
        with:
          github-token: ${secrets.GITHUB_TOKEN}
          script: |
            const output = ${{ process.env.DIff }}
            await core.summary
              .addHeading('cdk diff report')
              .addRaw(output)
              .write()
